version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - feastfinder-network
  
  rabbitmq-setup:
    build: ./rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    restart: on-failure
    networks:
      - feastfinder-network

  menu-service:
    build: ./services/simple/menu
    environment:
      - PORT=5000
    env_file:
      - .env
    ports:
      - "5003:5000"
    restart: on-failure
    networks:
      - feastfinder-network

  reservation-service:
    build: ./services/simple/reservation
    environment:
      - PORT=5000
    env_file:
      - .env
    ports:
      - "5002:5000"
    restart: on-failure
    networks:
      - feastfinder-network

  order-service:
    build: ./services/simple/order
    environment:
      - PORT=5000
    env_file:
      - .env
    ports:
      - "5004:5000"
    restart: on-failure
    networks:
      - feastfinder-network

  restaurant-service:
    build: ./services/simple/restaurant
    environment:
      - PORT=5000
    env_file:
      - .env
    ports:
      - "5001:5000"
    restart: on-failure
    networks:
      - feastfinder-network

  user-service:
    build: ./services/simple/user
    environment:
      - PORT=5000
    env_file:
      - .env
    ports:
      - "5000:5000"
    restart: on-failure
    networks:
      - feastfinder-network

  notification-service:
    build: ./services/simple/notification
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - PORT=5000
    env_file:
      - .env
    ports:
      - "5005:5000"
    restart: on-failure
    networks:
      - feastfinder-network

  payment-service:
    build: ./services/simple/payment
    environment:
      - PORT=5000
    env_file:
      - .env
    ports:
      - "5006:5000"
    restart: on-failure
    networks:
      - feastfinder-network

  create-booking-service:
    build: ./services/complex/create_booking
    depends_on:
      rabbitmq:
        condition: service_healthy
      menu-service:
        condition: service_started
      reservation-service:
        condition: service_started
      order-service:
        condition: service_started
      restaurant-service:
        condition: service_started
      user-service:
        condition: service_started
      notification-service:
        condition: service_started
      payment-service:
        condition: service_started
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - PORT=5000
      - USER_SERVICE_URL=http://user-service:5000
      - RESTAURANT_SERVICE_URL=http://restaurant-service:5000
      - ORDER_SERVICE_URL=http://order-service:5000
      - RESERVATION_SERVICE_URL=http://reservation-service:5000
      - MENU_SERVICE_URL=http://menu-service:5000
      - NOTIFICATION_SERVICE_URL=http://notification-service:5000
      - PAYMENT_SERVICE_URL=http://payment-service:5000
    env_file:
      - .env
    ports:
      - "5007:5000"
    restart: on-failure
    networks:
      - feastfinder-network

networks:
  feastfinder-network:
    driver: bridge 