version: '3.8'

volumes:
  rabbitmq_data:
    name: esd_rabbitmq_project
  db_data:
    name: esd_mysql_data

networks:
  esd-net:
    driver: bridge
    name: esd-net

services:

  ####################################
  # RabbitMQ: The messaging broker   
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"  
      - "15672:15672"  
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq 
    networks:
      - esd-net

  ####################################
  # MySQL Database Service   
  ####################################
  db:
    image: mysql:latest
    container_name: mysql-compose-container
    environment:
      MYSQL_DATABASE: waitlist
      MYSQL_ROOT_PASSWORD: "rootPW"  
    ports:
      - "3306:3306"  
    volumes:
      - db_data:/var/lib/mysql  
    networks:
      - esd-net
