version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"       # AMQP protocol port
      - "15672:15672"     # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - rabbitmq_network

  setup_rabbitmq:
    image: python:3.11-slim
    container_name: setup_rabbitmq
    depends_on:
      - rabbitmq
    networks:
      - rabbitmq_network
    volumes:
      - ./rabbitmq_setup.py:/app/rabbitmq_setup.py
    working_dir: /app
    command: >
      sh -c "pip install pika &&
             python rabbitmq_setup.py"
    environment:
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672

volumes:
  rabbitmq_data:

networks:
  rabbitmq_network: